#!/bin/bash
# Supabase Table Mismatch Fix
# 
# PROBLEM: Frontend queries 'civic_issues' but Backend uses 'incidents' table
# DATA IS IN: 'incidents' table (backend SQLAlchemy model)
# FRONTEND QUERIES: 'civic_issues' table (which may be empty)

echo "🔍 Supabase Table Investigation"
echo "================================"
echo ""
echo "Frontend Tables Used:"
echo "  - civic_issues (pages: index.js, dashboard.js, tickets.js, map-view.js)"
echo ""
echo "Backend Tables Used:"
echo "  - incidents (SQLAlchemy model in backend/app/models/incident.py)"
echo ""
echo "Storage Buckets:"
echo "  - issues (for images)"
echo "  - civic-issue-images (for Supabase storage)"
echo ""
echo "================================"
echo "SOLUTION: Drop old 'incidents' table OR migrate data to 'civic_issues'"
echo "================================"
echo ""
echo "Step 1: Go to Supabase Dashboard"
echo "Step 2: SQL Editor"
echo "Step 3: Run ONE of these:"
echo ""
echo "Option A - DROP old table (recommended if no data needed):"
echo "  DROP TABLE IF EXISTS incidents CASCADE;"
echo ""
echo "Option B - If you need the old data, migrate to new table:"
echo "  -- This would copy data from incidents to civic_issues"
echo "  -- But schema is different, so manual mapping needed"
echo ""
echo "Option C - Rename table (safest):"
echo "  ALTER TABLE incidents RENAME TO incidents_old;"
echo ""
echo "================================"
echo "After fix:"
echo "1. Restart frontend: npm run dev"
echo "2. Hard refresh: Ctrl+Shift+R"
echo "3. Check console: should see fresh data"
echo "================================"
